# Generated by Django 5.1.2 on 2024-10-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compnay_Profile',
            new_name='Candidate_Profile',
        ),
    ]
