# Generated by Django 5.1.2 on 2024-10-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0004_alter_apply_job_job_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='job_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
