# Generated by Django 5.1.2 on 2024-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0005_apply_job_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='status',
            field=models.CharField(default='Applied', max_length=100),
        ),
    ]
