# Generated by Django 5.1.2 on 2024-10-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0006_alter_apply_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
