# Generated by Django 5.1.2 on 2024-10-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0009_apply_job_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
