# Generated by Django 5.1.2 on 2024-10-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_user',
            name='type',
        ),
        migrations.AlterField(
            model_name='signup_user',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
