# Generated by Django 5.1.2 on 2024-10-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_jobs',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
