# Generated by Django 5.1.2 on 2024-10-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruter', '0002_add_jobs_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_jobs',
            name='application_count',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='add_jobs',
            name='job_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
