# Generated by Django 5.1.2 on 2024-10-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruter', '0003_add_jobs_application_count_add_jobs_job_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_jobs',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_jobs',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='add_jobs',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
