# Generated by Django 5.1.2 on 2024-10-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruter', '0004_add_jobs_age_add_jobs_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_jobs',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
