# Generated by Django 5.1.2 on 2024-10-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruter', '0005_alter_add_jobs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='compnay_profile',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
